// * By game settings
const ORIENTATION_CONFIG = {
    3200: { PORTRAIT: true, LANDSCAPE: false },
    3201: { PORTRAIT: true, LANDSCAPE: false },
    3202: { PORTRAIT: true, LANDSCAPE: false },
};

const EXTENSIONS_SCALE = 1;

const VIEW_CONFIG = {
    WIDTH: 360,
    HEIGHT: 640,
    CANVAS_WIDTH: 1500,
	CANVAS_HEIGHT: 640,
    UI_MIN_WIDTH: 1000,
};

//InGameMenu功能整合 @20231110 setting
const IN_GAME_MENU_ICON_CONTAINER_POSITION_X = 980;
const IN_GAME_MENU_ICON_CONTAINER_POSITION_Y =  25;
const IN_GAME_MENU_SLIDE_BUTTON_POSITION_X = 915;
const IN_GAME_MENU_SLIDE_BUTTON_POSITION_Y =  25;
const IN_GAME_MENU_MAIN_CONTAINER_ON_SLIDE_X = -130 ;
const IN_GAME_MENU_MAIN_CONTAINER_OFF_SLIDE_X = 0 ;
const IN_GAME_MENU_MAIN_CONTAINER_ON_SLIDE_X_HALF = -65 ;
const IN_GAME_MENU_MAIN_CONTAINER_RED_DOT_POSITION_X = 902 ;
const IN_GAME_MENU_MAIN_CONTAINER_RED_DOT_POSITION_Y = 5 ;
const PROMOTION_JACKPOT_CONTAINER_POSITION_X = -20 ;
const PROMOTION_JACKPOT_CONTAINER_POSITION_Y =   0 ;
const PROMOTION_PROMOTION_CONTAINER_POSITION_X = 40 ;
const PROMOTION_PROMOTION_CONTAINER_POSITION_Y =  0 ;
const PROMOTION_BUTTON_SCALE = 0.4 ;
const PROMOTION_JACKPOT_CONTAINER_RED_DOT_POSITION_X = 0 ;
const PROMOTION_JACKPOT_CONTAINER_RED_DOT_POSITION_Y = -7 ;
const PROMOTION_PROMOTION_CONTAINER_RED_DOT_POSITION_X = 55 ;
const PROMOTION_PROMOTION_CONTAINER_RED_DOT_POSITION_Y = -10 ;
const PROMOTION_JACKPOT_HINT_SHOW = -200;
const PROMOTION_JACKPOT_HINT_HIDE = 160;
const PROMOTION_JACKPOT_HINT_MASK_SHOW_POSITION_X = -360;
const PROMOTION_PROMOTION_HINT_SHOW = -270;
const PROMOTION_PROMOTION_HINT_HIDE = 120;
const PROMOTION_PROMOTION_HINT_MASK_SHOW_POSITION_X = -380;
const PROMOTION_PROMOTION_TEXT_POSITION_X = -100;